version: '3'
services:
  client:
    container_name: wildlife-refuge
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 80:3000
      - 9229:9229
    command:
      - start
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./img:/usr/src/app/img
